-- MySQL Script generated by MySQL Workbench
-- Mon Jul  4 10:46:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinalProject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FinalProject` ;

-- -----------------------------------------------------
-- Schema FinalProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinalProject` DEFAULT CHARACTER SET utf8 ;
USE `FinalProject` ;

-- -----------------------------------------------------
-- Table `FinalProject`.`Show`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinalProject`.`Show` ;

CREATE TABLE IF NOT EXISTS `FinalProject`.`Show` (
  `ShowId` INT NOT NULL AUTO_INCREMENT,
  `ShowTitle` VARCHAR(255) NOT NULL,
  `ShowType` INT NOT NULL,
  `ShowDescription` VARCHAR(1000) NOT NULL,
  `ShowTime` TIME NOT NULL,
  `ShowDate` DATE NOT NULL,
  `ShowDuration` TIME NOT NULL,
  `ShowCirclePrice` INT NOT NULL,
  `ShowStallPrice` INT NOT NULL,
  `ShowLanguage` VARCHAR(255) NOT NULL,
  `ShowMusicalAccompaniment` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ShowId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`MainPerformer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinalProject`.`MainPerformer` ;

CREATE TABLE IF NOT EXISTS `FinalProject`.`MainPerformer` (
  `MainPerformer` VARCHAR(255) NOT NULL,
  `ShowId` INT NOT NULL,
  INDEX `fk_MainPerformer_Show_idx` (`ShowId` ASC) VISIBLE,
  CONSTRAINT `fk_MainPerformer_Show`
    FOREIGN KEY (`ShowId`)
    REFERENCES `FinalProject`.`Show` (`ShowId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinalProject`.`Customer` ;

CREATE TABLE IF NOT EXISTS `FinalProject`.`Customer` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(255) NOT NULL,
  `CustomerAddress` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CustomerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinalProject`.`Booking` ;

CREATE TABLE IF NOT EXISTS `FinalProject`.`Booking` (
  `BookingId` INT NOT NULL AUTO_INCREMENT,
  `SeatType` INT NOT NULL,
  `SeatNumber` INT NOT NULL,
  `Concession` INT NOT NULL,
  `ShowId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  PRIMARY KEY (`BookingId`),
  INDEX `fk_Ticket_Show1_idx` (`ShowId` ASC) VISIBLE,
  INDEX `fk_Booking_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Show1`
    FOREIGN KEY (`ShowId`)
    REFERENCES `FinalProject`.`Show` (`ShowId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `FinalProject`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinalProject`.`Employee` ;

CREATE TABLE IF NOT EXISTS `FinalProject`.`Employee` (
  `EmployeeId` INT NOT NULL AUTO_INCREMENT,
  `EmployeeUsername` VARCHAR(255) NOT NULL,
  `EmployeePassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`EmployeeId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
